/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    brands: Brand;
    manufacturers: Manufacturer;
    units: Unit;
    attributes: Attribute;
    products: Product;
    variations: Variation;
    synonyms: Synonym;
    orders: Order;
    'import-profiles': ImportProfile;
    'import-runs': ImportRun;
    'import-logs': ImportLog;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    products: {
      variations: 'variations';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    brands: BrandsSelect<false> | BrandsSelect<true>;
    manufacturers: ManufacturersSelect<false> | ManufacturersSelect<true>;
    units: UnitsSelect<false> | UnitsSelect<true>;
    attributes: AttributesSelect<false> | AttributesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    variations: VariationsSelect<false> | VariationsSelect<true>;
    synonyms: SynonymsSelect<false> | SynonymsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    'import-profiles': ImportProfilesSelect<false> | ImportProfilesSelect<true>;
    'import-runs': ImportRunsSelect<false> | ImportRunsSelect<true>;
    'import-logs': ImportLogsSelect<false> | ImportLogsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('ro' | 'ru') | ('ro' | 'ru')[];
  globals: {
    homepage: Homepage;
    'search-settings': SearchSetting;
    'business-rules': BusinessRule;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    'search-settings': SearchSettingsSelect<false> | SearchSettingsSelect<true>;
    'business-rules': BusinessRulesSelect<false> | BusinessRulesSelect<true>;
  };
  locale: 'ro' | 'ru';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Text alternativ pentru accesibilitate și SEO.
   */
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    feature?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * Auto-generated from the name if left blank. Used in the URL.
   */
  slug: string;
  level: 'section' | 'category' | 'subcategory' | 'family';
  /**
   * The node one level up. Empty for a Section.
   */
  parent?: (number | null) | Category;
  /**
   * Supplier category strings that map to this node.
   */
  aliases?: string[] | null;
  heroImage?: (number | null) | Media;
  /**
   * Icon name for tiles/nav.
   */
  icon?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Editorial buying guide shown on the category page.
   */
  buyingGuide?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  featuredProducts?: (number | Product)[] | null;
  /**
   * Eligible for homepage Featured Categories.
   */
  featured?: boolean | null;
  /**
   * Lower numbers appear first.
   */
  displayOrder?: number | null;
  seo?: {
    /**
     * Defaults to the item name if left blank (~60 chars).
     */
    metaTitle?: string | null;
    /**
     * ~155 characters.
     */
    metaDescription?: string | null;
    /**
     * Social share image (Open Graph / Twitter).
     */
    ogImage?: (number | null) | Media;
    /**
     * Hide this page from search engines.
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  /**
   * Auto-generated from the name if left blank. Used in the URL.
   */
  slug: string;
  /**
   * Card text + meta description fallback.
   */
  shortDescription?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Domeniu de aplicare / Область применения.
   */
  applicationArea?: string | null;
  /**
   * Registry-driven. `key` references an Attribute; behaviour (filterable, etc.) comes from the registry.
   */
  attributes?:
    | {
        key: string;
        value: string;
        /**
         * Parsed numeric value for range filters/sorting (optional).
         */
        numericValue?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Default unit of sale.
   */
  unit?: (number | null) | Unit;
  countryOfOrigin?: string | null;
  barcode?: string | null;
  /**
   * kg (future).
   */
  netWeight?: number | null;
  /**
   * litres (future).
   */
  netVolume?: number | null;
  certifications?: string[] | null;
  primaryImage?: (number | null) | Media;
  gallery?: (number | Media)[] | null;
  /**
   * Installation/lifestyle images, technical drawings, PDFs, BIM (future).
   */
  assets?:
    | {
        type:
          | 'gallery'
          | 'installation'
          | 'lifestyle'
          | 'technical_drawing'
          | 'datasheet'
          | 'certificate'
          | 'manual'
          | 'bim'
          | 'other';
        file?: (number | null) | Media;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Priced variations (SKU). Managed in the Variations collection.
   */
  variations?: {
    docs?: (number | Variation)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  frequentlyBoughtTogether?: (number | Product)[] | null;
  similarProducts?: (number | Product)[] | null;
  betterAlternatives?: (number | Product)[] | null;
  premiumAlternatives?: (number | Product)[] | null;
  budgetAlternatives?: (number | Product)[] | null;
  compatibleProducts?: (number | Product)[] | null;
  accessories?: (number | Product)[] | null;
  consumables?: (number | Product)[] | null;
  replacementParts?: (number | Product)[] | null;
  /**
   * Search keywords / popular-search terms (manual or AI-generated).
   */
  keywords?: string[] | null;
  /**
   * Popularity signal used by search ranking.
   */
  popularity?: number | null;
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  enrichmentStatus?: ('none' | 'ai_suggested' | 'human_reviewed') | null;
  enrichedAt?: string | null;
  /**
   * Stable import identity (product base SKU).
   */
  legacyKey?: string | null;
  lifecycle:
    'draft' | 'active' | 'coming_soon' | 'out_of_stock' | 'price_on_request' | 'discontinued' | 'hidden' | 'archived';
  category?: (number | null) | Category;
  brand?: (number | null) | Brand;
  manufacturer?: (number | null) | Manufacturer;
  /**
   * Eligible for homepage Featured Products.
   */
  featured?: boolean | null;
  /**
   * Set by import when metadata (brand/unit/category) is missing.
   */
  needsReview?: boolean | null;
  /**
   * Why this product needs review.
   */
  reviewNotes?: string | null;
  /**
   * Maintained for full-text search (RO+RU+brand+category+specs).
   */
  searchText?: string | null;
  seo?: {
    /**
     * Defaults to the item name if left blank (~60 chars).
     */
    metaTitle?: string | null;
    /**
     * ~155 characters.
     */
    metaDescription?: string | null;
    /**
     * Social share image (Open Graph / Twitter).
     */
    ogImage?: (number | null) | Media;
    /**
     * Hide this page from search engines.
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "units".
 */
export interface Unit {
  id: number;
  code: string;
  label: string;
  symbol?: string | null;
  /**
   * Raw supplier unit strings mapping to this unit (e.g. "Kg", "saci").
   */
  aliases?: string[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variations".
 */
export interface Variation {
  id: number;
  product: number | Product;
  /**
   * Supplier/internal SKU. The synchronization key for imports.
   */
  sku: string;
  /**
   * EAN/barcode (future).
   */
  barcode?: string | null;
  /**
   * Price in MDL. Blank => "Preț la cerere".
   */
  price?: number | null;
  /**
   * Auto-enabled when there is no price.
   */
  priceOnRequest?: boolean | null;
  stockStatus?: ('in_stock' | 'low_stock' | 'out_of_stock') | null;
  /**
   * Auto-derived from attributes (e.g. "12,5 mm / Alb").
   */
  label?: string | null;
  attributes?:
    | {
        type:
          | 'thickness'
          | 'size'
          | 'length'
          | 'area'
          | 'colour'
          | 'quantity'
          | 'packaging_kg'
          | 'packaging_litres'
          | 'sheet'
          | 'per_m2'
          | 'door_opening'
          | 'door_dimensions'
          | 'eyelet'
          | 'other';
        label?: string | null;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands".
 */
export interface Brand {
  id: number;
  name: string;
  /**
   * Auto-generated from the name if left blank. Used in the URL.
   */
  slug: string;
  status?: ('active' | 'draft' | 'merged' | 'archived') | null;
  /**
   * Provenance, e.g. "import:liderconstruct-2024-05".
   */
  source?: string | null;
  logo?: (number | null) | Media;
  /**
   * Brand page hero banner.
   */
  banner?: (number | null) | Media;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  country?: string | null;
  website?: string | null;
  /**
   * Downloadable brand catalogues / price lists (PDF).
   */
  catalogues?:
    | {
        label?: string | null;
        file?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Supplier brand strings mapping here (e.g. "Euro As", "Euro AS").
   */
  aliases?: string[] | null;
  /**
   * Eligible for the homepage Top Brands section.
   */
  featured?: boolean | null;
  /**
   * Lower numbers appear first.
   */
  displayOrder?: number | null;
  seo?: {
    /**
     * Defaults to the item name if left blank (~60 chars).
     */
    metaTitle?: string | null;
    /**
     * ~155 characters.
     */
    metaDescription?: string | null;
    /**
     * Social share image (Open Graph / Twitter).
     */
    ogImage?: (number | null) | Media;
    /**
     * Hide this page from search engines.
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "manufacturers".
 */
export interface Manufacturer {
  id: number;
  name: string;
  /**
   * Auto-generated from the name if left blank. Used in the URL.
   */
  slug: string;
  country?: string | null;
  website?: string | null;
  description?: string | null;
  logo?: (number | null) | Media;
  /**
   * Supplier-provided manufacturer names that map here.
   */
  aliases?: string[] | null;
  seo?: {
    /**
     * Defaults to the item name if left blank (~60 chars).
     */
    metaTitle?: string | null;
    /**
     * ~155 characters.
     */
    metaDescription?: string | null;
    /**
     * Social share image (Open Graph / Twitter).
     */
    ogImage?: (number | null) | Media;
    /**
     * Hide this page from search engines.
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attributes".
 */
export interface Attribute {
  id: number;
  /**
   * Stable machine key (e.g. "thickness_mm"). Referenced by products.
   */
  key: string;
  displayName: string;
  dataType: 'text' | 'number' | 'boolean' | 'enum' | 'range' | 'dimension';
  /**
   * Specification block grouping.
   */
  group: 'technical' | 'dimensions' | 'packaging' | 'performance' | 'installation' | 'general';
  /**
   * Unit of measure for numeric/dimension attributes.
   */
  unit?: (number | null) | Unit;
  isSearchable?: boolean | null;
  isFilterable?: boolean | null;
  isSortable?: boolean | null;
  isComparable?: boolean | null;
  /**
   * Lower shows first in filters / spec sheets.
   */
  displayPriority?: number | null;
  /**
   * True if this attribute distinguishes variations (size, colour…).
   */
  appliesToVariation?: boolean | null;
  /**
   * Optional icon name (future UI).
   */
  icon?: string | null;
  /**
   * Allowed values for enum attributes (also seeds filter options).
   */
  options?:
    | {
        value: string;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Supplier column headers that map to this attribute.
   */
  aliases?: string[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "synonyms".
 */
export interface Synonym {
  id: number;
  term: string;
  synonyms: string[];
  kind?: ('synonym' | 'translation') | null;
  locale?: ('ro' | 'ru' | 'both') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  orderNumber?: number | null;
  /**
   * Order lifecycle — worked from this list.
   */
  status: 'noua' | 'contactata' | 'confirmata' | 'livrata' | 'inchisa' | 'anulata';
  language?: ('ro' | 'ru') | null;
  customer: {
    name: string;
    phone: string;
    email?: string | null;
    locality: string;
    address?: string | null;
    notes?: string | null;
  };
  items?:
    | {
        sku?: string | null;
        quantity: number;
        productTitle?: string | null;
        variationLabel?: string | null;
        /**
         * MDL. Blank = preț la cerere.
         */
        unitPrice?: number | null;
        priceOnRequest?: boolean | null;
        lineTotal?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Estimat — prețul final se confirmă la telefon (incl. livrare).
   */
  estimatedTotal?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "import-profiles".
 */
export interface ImportProfile {
  id: number;
  name: string;
  sourceFormat: 'ods' | 'xlsx' | 'csv' | 'tsv' | 'xml';
  /**
   * Sheet name for products (spreadsheets).
   */
  productsSheet?: string | null;
  /**
   * Sheet name for variations (if separate).
   */
  variationsSheet?: string | null;
  /**
   * CSV/TSV delimiter.
   */
  delimiter?: string | null;
  decimalSeparator?: ('.' | ',') | null;
  /**
   * Maps a source header to a canonical field or attribute key.
   */
  columnMap?:
    | {
        sourceHeader: string;
        targetField: string;
        kind?: ('field' | 'attribute' | 'variation_attribute') | null;
        id?: string | null;
      }[]
    | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "import-runs".
 */
export interface ImportRun {
  id: number;
  sourceFile: string;
  /**
   * SHA-256 of the source file.
   */
  checksum?: string | null;
  mode: 'full' | 'incremental' | 'price_only' | 'stock_only' | 'product_only' | 'dry_run';
  profile?: (number | null) | ImportProfile;
  status: 'pending' | 'running' | 'completed' | 'failed' | 'rolled_back';
  importedRows?: number | null;
  createdRows?: number | null;
  updatedRows?: number | null;
  skippedRows?: number | null;
  deletedRows?: number | null;
  warnings?: number | null;
  errors?: number | null;
  executionTimeMs?: number | null;
  user?: (number | null) | User;
  /**
   * Pre-write snapshot of affected records for rollback.
   */
  rollbackSnapshot?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Structured dry-run / execution report.
   */
  report?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  startedAt?: string | null;
  finishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "import-logs".
 */
export interface ImportLog {
  id: number;
  run?: (number | null) | ImportRun;
  rowNumber?: number | null;
  sku?: string | null;
  action?: ('create' | 'update' | 'skip' | 'quarantine' | 'warning' | 'error') | null;
  level?: ('info' | 'warning' | 'error') | null;
  field?: string | null;
  message?: string | null;
  suggestedFix?: string | null;
  sourceFile?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'brands';
        value: number | Brand;
      } | null)
    | ({
        relationTo: 'manufacturers';
        value: number | Manufacturer;
      } | null)
    | ({
        relationTo: 'units';
        value: number | Unit;
      } | null)
    | ({
        relationTo: 'attributes';
        value: number | Attribute;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'variations';
        value: number | Variation;
      } | null)
    | ({
        relationTo: 'synonyms';
        value: number | Synonym;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'import-profiles';
        value: number | ImportProfile;
      } | null)
    | ({
        relationTo: 'import-runs';
        value: number | ImportRun;
      } | null)
    | ({
        relationTo: 'import-logs';
        value: number | ImportLog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        feature?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  level?: T;
  parent?: T;
  aliases?: T;
  heroImage?: T;
  icon?: T;
  description?: T;
  buyingGuide?: T;
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  featuredProducts?: T;
  featured?: T;
  displayOrder?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands_select".
 */
export interface BrandsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  status?: T;
  source?: T;
  logo?: T;
  banner?: T;
  description?: T;
  country?: T;
  website?: T;
  catalogues?:
    | T
    | {
        label?: T;
        file?: T;
        id?: T;
      };
  aliases?: T;
  featured?: T;
  displayOrder?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "manufacturers_select".
 */
export interface ManufacturersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  country?: T;
  website?: T;
  description?: T;
  logo?: T;
  aliases?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "units_select".
 */
export interface UnitsSelect<T extends boolean = true> {
  code?: T;
  label?: T;
  symbol?: T;
  aliases?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attributes_select".
 */
export interface AttributesSelect<T extends boolean = true> {
  key?: T;
  displayName?: T;
  dataType?: T;
  group?: T;
  unit?: T;
  isSearchable?: T;
  isFilterable?: T;
  isSortable?: T;
  isComparable?: T;
  displayPriority?: T;
  appliesToVariation?: T;
  icon?: T;
  options?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  aliases?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  shortDescription?: T;
  description?: T;
  applicationArea?: T;
  attributes?:
    | T
    | {
        key?: T;
        value?: T;
        numericValue?: T;
        id?: T;
      };
  unit?: T;
  countryOfOrigin?: T;
  barcode?: T;
  netWeight?: T;
  netVolume?: T;
  certifications?: T;
  primaryImage?: T;
  gallery?: T;
  assets?:
    | T
    | {
        type?: T;
        file?: T;
        label?: T;
        id?: T;
      };
  variations?: T;
  frequentlyBoughtTogether?: T;
  similarProducts?: T;
  betterAlternatives?: T;
  premiumAlternatives?: T;
  budgetAlternatives?: T;
  compatibleProducts?: T;
  accessories?: T;
  consumables?: T;
  replacementParts?: T;
  keywords?: T;
  popularity?: T;
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  enrichmentStatus?: T;
  enrichedAt?: T;
  legacyKey?: T;
  lifecycle?: T;
  category?: T;
  brand?: T;
  manufacturer?: T;
  featured?: T;
  needsReview?: T;
  reviewNotes?: T;
  searchText?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variations_select".
 */
export interface VariationsSelect<T extends boolean = true> {
  product?: T;
  sku?: T;
  barcode?: T;
  price?: T;
  priceOnRequest?: T;
  stockStatus?: T;
  label?: T;
  attributes?:
    | T
    | {
        type?: T;
        label?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "synonyms_select".
 */
export interface SynonymsSelect<T extends boolean = true> {
  term?: T;
  synonyms?: T;
  kind?: T;
  locale?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  status?: T;
  language?: T;
  customer?:
    | T
    | {
        name?: T;
        phone?: T;
        email?: T;
        locality?: T;
        address?: T;
        notes?: T;
      };
  items?:
    | T
    | {
        sku?: T;
        quantity?: T;
        productTitle?: T;
        variationLabel?: T;
        unitPrice?: T;
        priceOnRequest?: T;
        lineTotal?: T;
        id?: T;
      };
  estimatedTotal?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "import-profiles_select".
 */
export interface ImportProfilesSelect<T extends boolean = true> {
  name?: T;
  sourceFormat?: T;
  productsSheet?: T;
  variationsSheet?: T;
  delimiter?: T;
  decimalSeparator?: T;
  columnMap?:
    | T
    | {
        sourceHeader?: T;
        targetField?: T;
        kind?: T;
        id?: T;
      };
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "import-runs_select".
 */
export interface ImportRunsSelect<T extends boolean = true> {
  sourceFile?: T;
  checksum?: T;
  mode?: T;
  profile?: T;
  status?: T;
  importedRows?: T;
  createdRows?: T;
  updatedRows?: T;
  skippedRows?: T;
  deletedRows?: T;
  warnings?: T;
  errors?: T;
  executionTimeMs?: T;
  user?: T;
  rollbackSnapshot?: T;
  report?: T;
  startedAt?: T;
  finishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "import-logs_select".
 */
export interface ImportLogsSelect<T extends boolean = true> {
  run?: T;
  rowNumber?: T;
  sku?: T;
  action?: T;
  level?: T;
  field?: T;
  message?: T;
  suggestedFix?: T;
  sourceFile?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  sections?:
    | (
        | {
            title?: string | null;
            subtitle?: string | null;
            /**
             * Pick top-level Section nodes from the internal taxonomy.
             */
            sections?: (number | Category)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featuredSections';
          }
        | {
            title?: string | null;
            subtitle?: string | null;
            categories?: (number | Category)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featuredCategories';
          }
        | {
            title?: string | null;
            subtitle?: string | null;
            brands?: (number | Brand)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featuredBrands';
          }
        | {
            title?: string | null;
            subtitle?: string | null;
            products?: (number | Product)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featuredProducts';
          }
        | {
            title?: string | null;
            subtitle?: string | null;
            terms?:
              | {
                  label: string;
                  query: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'popularSearches';
          }
        | {
            title?: string | null;
            subtitle?: string | null;
            source?: ('popular' | 'new' | 'recent' | 'promotions') | null;
            limit?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'productQuery';
          }
        | {
            title?: string | null;
            subtitle?: string | null;
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            image?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'editorial';
          }
      )[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search-settings".
 */
export interface SearchSetting {
  id: number;
  weightExactSku?: number | null;
  weightExactName?: number | null;
  weightBrand?: number | null;
  weightCategory?: number | null;
  weightPopularity?: number | null;
  weightFeatured?: number | null;
  weightAvailability?: number | null;
  weightKeywords?: number | null;
  weightSynonyms?: number | null;
  typoTolerance?: boolean | null;
  /**
   * Informational; actual driver is set via SEARCH_DRIVER.
   */
  engine?: ('postgres' | 'meilisearch' | 'ai') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "business-rules".
 */
export interface BusinessRule {
  id: number;
  status?: {
    /**
     * All variations without a price → "Price on Request".
     */
    priceOnRequestWhenNoPrice?: boolean | null;
    /**
     * No in-stock/low-stock variation → "Hidden".
     */
    hiddenWhenNoActiveVariation?: boolean | null;
    /**
     * Supplier-flagged discontinued → "Discontinued".
     */
    discontinuedFromSupplierFlag?: boolean | null;
    needsReviewWhenMissing?: ('brand' | 'unit' | 'category')[] | null;
  };
  seo?: {
    /**
     * Generate SEO only when fields are empty — manual edits always win.
     */
    generateWhenEmpty?: boolean | null;
    titleTemplate?: string | null;
    maxTitle?: number | null;
    maxDescription?: number | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  sections?:
    | T
    | {
        featuredSections?:
          | T
          | {
              title?: T;
              subtitle?: T;
              sections?: T;
              id?: T;
              blockName?: T;
            };
        featuredCategories?:
          | T
          | {
              title?: T;
              subtitle?: T;
              categories?: T;
              id?: T;
              blockName?: T;
            };
        featuredBrands?:
          | T
          | {
              title?: T;
              subtitle?: T;
              brands?: T;
              id?: T;
              blockName?: T;
            };
        featuredProducts?:
          | T
          | {
              title?: T;
              subtitle?: T;
              products?: T;
              id?: T;
              blockName?: T;
            };
        popularSearches?:
          | T
          | {
              title?: T;
              subtitle?: T;
              terms?:
                | T
                | {
                    label?: T;
                    query?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        productQuery?:
          | T
          | {
              title?: T;
              subtitle?: T;
              source?: T;
              limit?: T;
              id?: T;
              blockName?: T;
            };
        editorial?:
          | T
          | {
              title?: T;
              subtitle?: T;
              content?: T;
              image?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search-settings_select".
 */
export interface SearchSettingsSelect<T extends boolean = true> {
  weightExactSku?: T;
  weightExactName?: T;
  weightBrand?: T;
  weightCategory?: T;
  weightPopularity?: T;
  weightFeatured?: T;
  weightAvailability?: T;
  weightKeywords?: T;
  weightSynonyms?: T;
  typoTolerance?: T;
  engine?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "business-rules_select".
 */
export interface BusinessRulesSelect<T extends boolean = true> {
  status?:
    | T
    | {
        priceOnRequestWhenNoPrice?: T;
        hiddenWhenNoActiveVariation?: T;
        discontinuedFromSupplierFlag?: T;
        needsReviewWhenMissing?: T;
      };
  seo?:
    | T
    | {
        generateWhenEmpty?: T;
        titleTemplate?: T;
        maxTitle?: T;
        maxDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}